apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas:3
  selector:
    matchlabels:
      component: web
    template:
      metadata:
        labels:
          component: web
      spec:
        containers:
          - name: client
            image: stephengtider/multiclient
            ports:
              - containerPort: 3000